services:
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    depends_on:
      - frontend
      - backend
      - meilisearch
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    networks:
      - net

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - net

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - meilisearch
      - postgres
    environment:
      - MEILISEARCH_URL=http://meilisearch:7700
      - DATABASE_URL=postgres://a3_admin:db_password@postgres:5432/artemis3
    networks:
      - net

  meilisearch:
    image: getmeili/meilisearch:v1.16
    container_name: meilisearch
    ports:
      - "7700:7700"
    volumes:
      - meilisearch:/meili_data
    environment:
      - MEILI_ENV=development
      - MEILI_HTTP_ADDR=0.0.0.0:7700
    networks:
      - net
      
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_USER=a3_admin
      - POSTGRES_PASSWORD=db_password
      - POSTGRES_DB=artemis3
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - net

networks:
  net:
    driver: bridge

volumes:
  meilisearch:
  postgres_data:
